name: Build & Deploy LaTeX Project

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            main.tex
          sparse-checkout-cone-mode: false

      # Compiles
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      # Uploads the PDF
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf
