name: Build & Deploy LaTeX Project

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            main.tex
          sparse-checkout-cone-mode: false

      # Compiles
      - name: Build Latex PDF and HTML
        run: |
          sudo apt update
          sudo apt install texlive-full
          mkdir ./public
          cp main.tex public/
          cd public/
          pdflatex main.tex
          make4ht main.tex
          mv main.html index.html

      # Uploads the PDF
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: public/main.pdf

      # Publishes the PDF as a release
      - name: Publish PDF
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Current
          files: public/main.pdf

      # Publish HTML to GitHub Pages
      - name: Publish HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
